<?php

namespace Modules\RequisitionSystem\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\RequisitionSystem\Models\ChartOfAccount;

class ChartOfAccountSeeder extends Seeder
{
    public function run(): void
    {
        $accounts = [
            ['account_no' => '70101', 'description' => 'Salaries (Full Time Permanent)'],
            ['account_no' => '70102', 'description' => 'Salaries (Adjunct)'],
            ['account_no' => '70103', 'description' => 'Wages (Un-established Staff)'],
            ['account_no' => '70103.1', 'description' => 'Wages - Overtime'],
            ['account_no' => '70104', 'description' => 'Allowances'],
            ['account_no' => '70105', 'description' => 'Social Security Contribution'],
            ['account_no' => '70106', 'description' => 'Honorarium'],
            ['account_no' => '70107', 'description' => 'Ex-Gratia Payment'],
            ['account_no' => '70108', 'description' => 'Pensions'],
            ['account_no' => '70109', 'description' => 'Gratuities (Contractual)'],
            ['account_no' => '70110', 'description' => 'Gratuities (10 yrs +)'],
            ['account_no' => '70111', 'description' => 'Health Insurance (Life, Medical, Dental, Optical)'],
            ['account_no' => '70112', 'description' => 'Study Leave Replacement'],
            ['account_no' => '70113', 'description' => 'Promotion for Assoc. Prof.'],
            ['account_no' => '70114', 'description' => 'Promotion Senior Lecturer'],
            ['account_no' => '70115', 'description' => 'Severance Expense'],
            ['account_no' => '70116', 'description' => 'Vacation Expense'],
            ['account_no' => '71112', 'description' => 'Off Sequence'],
            ['account_no' => '71114', 'description' => 'Deferred Exam'],
            ['account_no' => '70201', 'description' => 'Mileage'],
            ['account_no' => '70202', 'description' => 'Subsistence'],
            ['account_no' => '70203', 'description' => 'Foreign Travel'],
            ['account_no' => '70204', 'description' => 'Other Travel Expenses'],
            ['account_no' => '70301', 'description' => 'Office Supplies'],
            ['account_no' => '70302', 'description' => 'Books & Periodicals'],
            ['account_no' => '70303', 'description' => 'Medical & Laboratory Supplies'],
            ['account_no' => '70304', 'description' => 'Uniforms'],
            ['account_no' => '70305', 'description' => 'Household Sundries'],
            ['account_no' => '70306', 'description' => 'Food'],
            ['account_no' => '70307', 'description' => 'Spraying Supplies'],
            ['account_no' => '70308', 'description' => 'Spares - Farm Machinery Equip.'],
            ['account_no' => '70309', 'description' => 'Animal Feed'],
            ['account_no' => '70310', 'description' => 'Animal Pasture'],
            ['account_no' => '70311', 'description' => 'Production Supplies'],
            ['account_no' => '70312', 'description' => 'School Supplies'],
            ['account_no' => '70313', 'description' => 'Building & Construction'],
            ['account_no' => '70314', 'description' => 'Computer Supplies'],
            ['account_no' => '70315', 'description' => 'Other Office Equipment'],
            ['account_no' => '70316', 'description' => 'Other Laboratory Supplies'],
            ['account_no' => '70317', 'description' => 'Test Equipment'],
            ['account_no' => '70318', 'description' => 'Other Equipment'],
            ['account_no' => '70319', 'description' => 'Teaching Supplies'],
            ['account_no' => '71318', 'description' => 'Meals Supplies'],
            ['account_no' => '70401', 'description' => 'Fuel'],
            ['account_no' => '70402', 'description' => 'Advertising'],
            ['account_no' => '70403', 'description' => 'Miscellaneous'],
            ['account_no' => '70404', 'description' => 'Building Construction'],
            ['account_no' => '70405', 'description' => 'Mail Delivery'],
            ['account_no' => '70406', 'description' => 'Office Cleaning (House Keeping)'],
            ['account_no' => '70407', 'description' => 'Garbage Disposal'],
            ['account_no' => '70409', 'description' => 'Insurance - Computers'],
            ['account_no' => '70410', 'description' => 'Insurance - Buildings'],
            ['account_no' => '70411', 'description' => 'Insurance - Furniture & Fixture'],
            ['account_no' => '70412', 'description' => 'Insurance - Motor Vehicles'],
            ['account_no' => '70413', 'description' => 'Insurance - Liab & Other'],
            ['account_no' => '70414', 'description' => 'Bank Charges'],
            ['account_no' => '70415', 'description' => 'Bereavement Expeneses'],
            ['account_no' => '70416', 'description' => 'Employment Expense'],
            ['account_no' => '70417', 'description' => 'Entertainment'],
            ['account_no' => '70418', 'description' => 'Insurance - - Machinery & Equip'],
            ['account_no' => '70419', 'description' => 'Tax Assessmnt/Soc Sec Penalties'],
            ['account_no' => '70422', 'description' => 'Collection Expense'],
            ['account_no' => '70423', 'description' => 'Loss on Exchange Rate/Shortage'],
            ['account_no' => '70424', 'description' => 'Capital Financing Costs'],
            ['account_no' => '71101', 'description' => 'Recruitment'],
            ['account_no' => '71102', 'description' => 'Orientation'],
            ['account_no' => '71103', 'description' => 'Registration'],
            ['account_no' => '71104', 'description' => 'Graduation'],
            ['account_no' => '71105', 'description' => 'Physical Education & Sports'],
            ['account_no' => '71106', 'description' => 'Field Trips'],
            ['account_no' => '71107', 'description' => 'Programming'],
            ['account_no' => '71107.1', 'description' => 'UB Anniversary'],
            ['account_no' => '71107.2', 'description' => 'Recognition & Awards'],
            ['account_no' => '71107.3', 'description' => 'Socializing'],
            ['account_no' => '71107.4', 'description' => 'Donation'],
            ['account_no' => '71108', 'description' => 'Student Services'],
            ['account_no' => '71109', 'description' => 'Publications / Reports'],
            ['account_no' => '71110', 'description' => 'RLC stipend'],
            ['account_no' => '71111', 'description' => 'UB Scholarships'],
            ['account_no' => '71116', 'description' => 'Sponsorship Expense'],
            ['account_no' => '71204', 'description' => 'Brokerage/ Custome Fees'],
            ['account_no' => '70501', 'description' => 'Maintenance of Buildings'],
            ['account_no' => '70502', 'description' => 'Maintenance of Grounds'],
            ['account_no' => '70503', 'description' => 'Repairs & Maintenance of Furn. & Equip.'],
            ['account_no' => '70504', 'description' => 'Repairs & Maintenance of Vehicles'],
            ['account_no' => '70523', 'description' => 'Rep. & Maint-Computer Hardware'],
            ['account_no' => '70524', 'description' => 'Rep. & Maint-Computer Software'],
            ['account_no' => '70525', 'description' => 'Maintenance of Classroom & Lab. Equip.'],
            ['account_no' => '70526', 'description' => 'Maintenance of Other Equipment'],
            ['account_no' => '70537', 'description' => 'Depreciation'],
            ['account_no' => '70408', 'description' => 'Conference'],
            ['account_no' => '70601', 'description' => 'Courses/Seminars'],
            ['account_no' => '70602', 'description' => 'Workshops'],
            ['account_no' => '70603', 'description' => 'Training Books and Materials'],
            ['account_no' => '70701', 'description' => 'Compensation - Auditing'],
            ['account_no' => '70702', 'description' => 'Compensation - Legal'],
            ['account_no' => '70703', 'description' => 'Consultancy'],
            ['account_no' => '70704', 'description' => 'Service Contract'],
            ['account_no' => '70704.1', 'description' => 'Service Agreement'],
            ['account_no' => '70705', 'description' => 'Translation'],
            ['account_no' => '71202', 'description' => 'Other Outside Services'],
            ['account_no' => '70801', 'description' => 'Electricity'],
            ['account_no' => '70802', 'description' => 'Gas - Butane'],
            ['account_no' => '70803', 'description' => 'Water'],
            ['account_no' => '70804', 'description' => 'Telephones'],
            ['account_no' => '70805', 'description' => 'Internet'],
            ['account_no' => '70901', 'description' => 'Individual Research'],
            ['account_no' => '70902', 'description' => 'ATLIB'],
            ['account_no' => '70904', 'description' => 'COBEC'],
            ['account_no' => '70905', 'description' => 'CSUCA'],
            ['account_no' => '70906', 'description' => 'Others'],
            ['account_no' => '70920', 'description' => 'UB Scholarships & Grants'],
            ['account_no' => '71001', 'description' => 'Rental of Office Space'],
            ['account_no' => '71002', 'description' => 'Housing for Visiting Faculty'],
            ['account_no' => '71003', 'description' => 'Rental of Other Buildings'],
            ['account_no' => '71004', 'description' => 'Rental of Office Equipment'],
            ['account_no' => '71005', 'description' => 'Rental of Other Equipment'],
            ['account_no' => '71006', 'description' => 'Rental of Vehicles'],
            ['account_no' => '71007', 'description' => 'Other Rentals'],
            ['account_no' => '71113', 'description' => 'Contingencies'],
            ['account_no' => '72001', 'description' => 'Loss on write-down inventory'],
            ['account_no' => '72002', 'description' => 'Bad Debt Expense'],
            ['account_no' => '72003', 'description' => 'Loss on Disposal of Assets'],
            ['account_no' => '15101', 'description' => 'Land & Land Improvements'],
            ['account_no' => '15102', 'description' => 'Buildings & Bldg Improvements'],
            ['account_no' => '15103', 'description' => 'Office Furniture & Fixtures'],
            ['account_no' => '15104', 'description' => 'Motor Vehilces'],
            ['account_no' => '15105', 'description' => 'Computer & Equipment'],
            ['account_no' => '15106', 'description' => 'Machinery & Equipment'],
            ['account_no' => '15107', 'description' => 'Lab Equipment'],
            ['account_no' => '15109', 'description' => 'Capital Work in Progresss'],
        ];

        ChartOfAccount::upsert($accounts, ['account_no'], ['description']);
    }
}
