<?php

namespace Modules\RequisitionSystem\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\RequisitionSystem\Models\ChartOfAccount;

class ChartOfAccountSeeder extends Seeder
{
    public function run(): void
    {
        // Synced from live chart_of_accounts (157 accounts).
        $accounts = [
            ['account_no' => '15100', 'description' => 'Capital Expenditures'],
            ['account_no' => '15101', 'description' => 'Land & Land Improvements', 'parent_account_no' => '15100'],
            ['account_no' => '15102', 'description' => 'Buildings & Bldg Improvements', 'parent_account_no' => '15100'],
            ['account_no' => '15103', 'description' => 'Office Furniture & Fixtures', 'parent_account_no' => '15100'],
            ['account_no' => '15104', 'description' => 'Motor Vehilces', 'parent_account_no' => '15100'],
            ['account_no' => '15105', 'description' => 'Computer & Equipment', 'parent_account_no' => '15100'],
            ['account_no' => '15106', 'description' => 'Machinery & Equipment', 'parent_account_no' => '15100'],
            ['account_no' => '15107', 'description' => 'Lab Equipment', 'parent_account_no' => '15100'],
            ['account_no' => '15109', 'description' => 'Capital Work in Progresss', 'parent_account_no' => '15100'],
            ['account_no' => '61100', 'description' => 'Tuition and Fees Current Year'],
            ['account_no' => '61200', 'description' => 'Tuition and Fees Accrued'],
            ['account_no' => '61300', 'description' => 'Government of Belize - Subvention'],
            ['account_no' => '61600', 'description' => 'Agri-Business - Central Farm'],
            ['account_no' => '61700', 'description' => 'Calabash Caye Field Station'],
            ['account_no' => '61902', 'description' => 'Online Distance Learning (ODL)'],
            ['account_no' => '62301', 'description' => 'UB FEA Academy'],
            ['account_no' => '62500', 'description' => 'Interest Income'],
            ['account_no' => '62600', 'description' => 'Other Income'],
            ['account_no' => '62606', 'description' => 'Account 62606'],
            ['account_no' => '62612', 'description' => 'Course Outlines'],
            ['account_no' => '63501', 'description' => 'Capital Grant Revenue'],
            ['account_no' => '70100', 'description' => 'Personal Emoluments'],
            ['account_no' => '70101', 'description' => 'Salaries (Full Time Permanent)', 'parent_account_no' => '70100'],
            ['account_no' => '70102', 'description' => 'Salaries (Adjunct)', 'parent_account_no' => '70100'],
            ['account_no' => '70103', 'description' => 'Wages (Un-established Staff)', 'parent_account_no' => '70100'],
            ['account_no' => '70103.1', 'description' => 'Wages (Overtime)', 'parent_account_no' => '70103'],
            ['account_no' => '70104', 'description' => 'Allowances', 'parent_account_no' => '70100'],
            ['account_no' => '70105', 'description' => 'Social Security', 'parent_account_no' => '70100'],
            ['account_no' => '70106', 'description' => 'Honorarium', 'parent_account_no' => '70100'],
            ['account_no' => '70107', 'description' => 'Ex-Gratia Payment', 'parent_account_no' => '70100'],
            ['account_no' => '70108', 'description' => 'Pensions (UB Liabilities)', 'parent_account_no' => '70100'],
            ['account_no' => '70109', 'description' => 'Gratuities (Contractual)', 'parent_account_no' => '70100'],
            ['account_no' => '70110', 'description' => 'Gratuities (10 years + gratuities liability)', 'parent_account_no' => '70100'],
            ['account_no' => '70111', 'description' => 'Health Insurance (Life, Medical, Dental, Optical)', 'parent_account_no' => '70100'],
            ['account_no' => '70112', 'description' => 'Study Leave Replacement', 'parent_account_no' => '70100'],
            ['account_no' => '70113', 'description' => 'Promotion for Assoc. Prof.', 'parent_account_no' => '70100'],
            ['account_no' => '70114', 'description' => 'Promotion Senior Lecturer', 'parent_account_no' => '70100'],
            ['account_no' => '70115', 'description' => 'Severance Expense', 'parent_account_no' => '70100'],
            ['account_no' => '70116', 'description' => 'Vacation Expense', 'parent_account_no' => '70100'],
            ['account_no' => '70200', 'description' => 'Travel & Subsistence'],
            ['account_no' => '70201', 'description' => 'Mileage', 'parent_account_no' => '70200'],
            ['account_no' => '70202', 'description' => 'Subsistence', 'parent_account_no' => '70200'],
            ['account_no' => '70203', 'description' => 'Foreign Travel', 'parent_account_no' => '70200'],
            ['account_no' => '70204', 'description' => 'Other Travel Expenditures', 'parent_account_no' => '70200'],
            ['account_no' => '70300', 'description' => 'Materials & Supplies'],
            ['account_no' => '70301', 'description' => 'Office Supplies', 'parent_account_no' => '70300'],
            ['account_no' => '70302', 'description' => 'Books & Periodicals', 'parent_account_no' => '70300'],
            ['account_no' => '70303', 'description' => 'Medical & Laboratory Supplies', 'parent_account_no' => '70300'],
            ['account_no' => '70304', 'description' => 'Uniforms', 'parent_account_no' => '70300'],
            ['account_no' => '70305', 'description' => 'Household Sundries', 'parent_account_no' => '70300'],
            ['account_no' => '70306', 'description' => 'Food', 'parent_account_no' => '70300'],
            ['account_no' => '70307', 'description' => 'Spraying Supplies', 'parent_account_no' => '70300'],
            ['account_no' => '70308', 'description' => 'Spares - Farm Machinery Equip.', 'parent_account_no' => '70300'],
            ['account_no' => '70309', 'description' => 'Animal Feed', 'parent_account_no' => '70300'],
            ['account_no' => '70310', 'description' => 'Animal Pasture', 'parent_account_no' => '70300'],
            ['account_no' => '70311', 'description' => 'Production Supplies', 'parent_account_no' => '70300'],
            ['account_no' => '70312', 'description' => 'School Supplies', 'parent_account_no' => '70300'],
            ['account_no' => '70313', 'description' => 'Building & Construction Supplies', 'parent_account_no' => '70300'],
            ['account_no' => '70314', 'description' => 'Computer Supplies', 'parent_account_no' => '70300'],
            ['account_no' => '70315', 'description' => 'Other Office Equipment', 'parent_account_no' => '70300'],
            ['account_no' => '70316', 'description' => 'Other Laboratory Supplies', 'parent_account_no' => '70300'],
            ['account_no' => '70317', 'description' => 'Test Equipment', 'parent_account_no' => '70300'],
            ['account_no' => '70318', 'description' => 'Other Equipment', 'parent_account_no' => '70300'],
            ['account_no' => '70319', 'description' => 'Teaching Supplies', 'parent_account_no' => '70300'],
            ['account_no' => '70400', 'description' => 'Operating Costs'],
            ['account_no' => '70401', 'description' => 'Fuel', 'parent_account_no' => '70400'],
            ['account_no' => '70402', 'description' => 'Advertising', 'parent_account_no' => '70400'],
            ['account_no' => '70403', 'description' => 'Miscellaneous', 'parent_account_no' => '70400'],
            ['account_no' => '70404', 'description' => 'Building Construction', 'parent_account_no' => '70400'],
            ['account_no' => '70405', 'description' => 'Mail Delivery', 'parent_account_no' => '70400'],
            ['account_no' => '70406', 'description' => 'Office Cleaning (House Keeping)', 'parent_account_no' => '70400'],
            ['account_no' => '70407', 'description' => 'Garbage Disposal', 'parent_account_no' => '70400'],
            ['account_no' => '70408', 'description' => 'Conference', 'parent_account_no' => '70600'],
            ['account_no' => '70409', 'description' => 'Insurance - Computers', 'parent_account_no' => '70400'],
            ['account_no' => '70410', 'description' => 'Insurance - Buildings', 'parent_account_no' => '70400'],
            ['account_no' => '70411', 'description' => 'Insurance - Furniture, Equipment', 'parent_account_no' => '70400'],
            ['account_no' => '70412', 'description' => 'Insurance - Motor Vehicles', 'parent_account_no' => '70400'],
            ['account_no' => '70413', 'description' => 'Insurance - Liab & Other', 'parent_account_no' => '70400'],
            ['account_no' => '70414', 'description' => 'Bank Charges', 'parent_account_no' => '70400'],
            ['account_no' => '70415', 'description' => 'Bereavement Expeneses', 'parent_account_no' => '70400'],
            ['account_no' => '70416', 'description' => 'Employment Expense', 'parent_account_no' => '70400'],
            ['account_no' => '70417', 'description' => 'Entertainment', 'parent_account_no' => '70400'],
            ['account_no' => '70418', 'description' => 'Insurance - - Machinery & Equip', 'parent_account_no' => '70400'],
            ['account_no' => '70419', 'description' => 'Tax Assessmnt/Soc Sec Penalties', 'parent_account_no' => '70400'],
            ['account_no' => '70422', 'description' => 'Collection Expense', 'parent_account_no' => '70400'],
            ['account_no' => '70423', 'description' => 'Loss on Exchange Rate', 'parent_account_no' => '70400'],
            ['account_no' => '70424', 'description' => 'Capital Financing Costs', 'parent_account_no' => '70400'],
            ['account_no' => '70500', 'description' => 'Maintenance Costs'],
            ['account_no' => '70501', 'description' => 'Maintenance of Buildings', 'parent_account_no' => '70500'],
            ['account_no' => '70502', 'description' => 'Maintenance of Grounds', 'parent_account_no' => '70500'],
            ['account_no' => '70503', 'description' => 'Repairs & Maintenance of Furn. & Equip.', 'parent_account_no' => '70500'],
            ['account_no' => '70504', 'description' => 'Repairs & Maintenance of Vehicles', 'parent_account_no' => '70500'],
            ['account_no' => '70523', 'description' => 'Maintenance of Computer Hardware', 'parent_account_no' => '70500'],
            ['account_no' => '70524', 'description' => 'Maintenance of Computer Software', 'parent_account_no' => '70500'],
            ['account_no' => '70525', 'description' => 'Maintenance of Classroom & Lab. Equip.', 'parent_account_no' => '70500'],
            ['account_no' => '70526', 'description' => 'Maintenance of Other Equipment', 'parent_account_no' => '70500'],
            ['account_no' => '70537', 'description' => 'Depreciation Expense'],
            ['account_no' => '70600', 'description' => 'Training'],
            ['account_no' => '70601', 'description' => 'Courses/Seminars', 'parent_account_no' => '70600'],
            ['account_no' => '70602', 'description' => 'Workshops', 'parent_account_no' => '70600'],
            ['account_no' => '70603', 'description' => 'Training Books and Materials', 'parent_account_no' => '70600'],
            ['account_no' => '70700', 'description' => 'Professional Services'],
            ['account_no' => '70701', 'description' => 'Compensation - Auditing', 'parent_account_no' => '70700'],
            ['account_no' => '70702', 'description' => 'Compensation - Legal', 'parent_account_no' => '70700'],
            ['account_no' => '70703', 'description' => 'Consultancy', 'parent_account_no' => '70700'],
            ['account_no' => '70704', 'description' => 'Service Contract', 'parent_account_no' => '70700'],
            ['account_no' => '70704.1', 'description' => 'Service Agreement', 'parent_account_no' => '70704'],
            ['account_no' => '70705', 'description' => 'Translation', 'parent_account_no' => '70700'],
            ['account_no' => '70800', 'description' => 'Public Utilities'],
            ['account_no' => '70801', 'description' => 'Electricity', 'parent_account_no' => '70800'],
            ['account_no' => '70802', 'description' => 'Gas - Butane', 'parent_account_no' => '70800'],
            ['account_no' => '70803', 'description' => 'Water', 'parent_account_no' => '70800'],
            ['account_no' => '70804', 'description' => 'Telephones', 'parent_account_no' => '70800'],
            ['account_no' => '70805', 'description' => 'Internet', 'parent_account_no' => '70800'],
            ['account_no' => '70900', 'description' => 'Contributions, Licences & Subscriptions'],
            ['account_no' => '70901', 'description' => 'Individual Research', 'parent_account_no' => '70900'],
            ['account_no' => '70902', 'description' => 'ATLIB', 'parent_account_no' => '70900'],
            ['account_no' => '70903', 'description' => 'ACTI', 'parent_account_no' => '70900'],
            ['account_no' => '70904', 'description' => 'COBEC', 'parent_account_no' => '70900'],
            ['account_no' => '70905', 'description' => 'CSUCA', 'parent_account_no' => '70900'],
            ['account_no' => '70906', 'description' => 'Others', 'parent_account_no' => '70900'],
            ['account_no' => '70920', 'description' => 'UB Scholarships & Grants'],
            ['account_no' => '71000', 'description' => 'Rents'],
            ['account_no' => '71001', 'description' => 'Rental of Office Space', 'parent_account_no' => '71000'],
            ['account_no' => '71002', 'description' => 'Housing for Visiting Faculty', 'parent_account_no' => '71000'],
            ['account_no' => '71003', 'description' => 'Rental of Other Buildings', 'parent_account_no' => '71000'],
            ['account_no' => '71004', 'description' => 'Rental of Office Equipment', 'parent_account_no' => '71000'],
            ['account_no' => '71005', 'description' => 'Rental of Other Equipment', 'parent_account_no' => '71000'],
            ['account_no' => '71006', 'description' => 'Rental of Vehicles', 'parent_account_no' => '71000'],
            ['account_no' => '71007', 'description' => 'Other Rentals', 'parent_account_no' => '71000'],
            ['account_no' => '71101', 'description' => 'Recruitment', 'parent_account_no' => '70400'],
            ['account_no' => '71102', 'description' => 'Orientation', 'parent_account_no' => '70400'],
            ['account_no' => '71103', 'description' => 'Registration', 'parent_account_no' => '70400'],
            ['account_no' => '71104', 'description' => 'Graduation', 'parent_account_no' => '70400'],
            ['account_no' => '71105', 'description' => 'Physical Education & Sports', 'parent_account_no' => '70400'],
            ['account_no' => '71106', 'description' => 'Field Trips', 'parent_account_no' => '70400'],
            ['account_no' => '71107', 'description' => 'Programming', 'parent_account_no' => '70400'],
            ['account_no' => '71107.1', 'description' => 'UB Anniversary', 'parent_account_no' => '71107'],
            ['account_no' => '71107.2', 'description' => 'Recognition & Awards', 'parent_account_no' => '71107'],
            ['account_no' => '71107.3', 'description' => 'Socializing', 'parent_account_no' => '71107'],
            ['account_no' => '71107.4', 'description' => 'Donation', 'parent_account_no' => '71107'],
            ['account_no' => '71108', 'description' => 'Student Services', 'parent_account_no' => '70400'],
            ['account_no' => '71109', 'description' => 'Publications / Reports', 'parent_account_no' => '70400'],
            ['account_no' => '71110', 'description' => 'RLC stipend', 'parent_account_no' => '70400'],
            ['account_no' => '71111', 'description' => 'UB Scholarships', 'parent_account_no' => '70400'],
            ['account_no' => '71112', 'description' => 'Off Sequence', 'parent_account_no' => '70100'],
            ['account_no' => '71113', 'description' => 'Contingencies'],
            ['account_no' => '71114', 'description' => 'Deferred Exam', 'parent_account_no' => '70100'],
            ['account_no' => '71115', 'description' => 'Discount', 'parent_account_no' => '71113'],
            ['account_no' => '71116', 'description' => 'Sponsorship Expense', 'parent_account_no' => '70400'],
            ['account_no' => '71202', 'description' => 'Other Outside Services', 'parent_account_no' => '70700'],
            ['account_no' => '71204', 'description' => 'Brokerage/ Custome Fees', 'parent_account_no' => '70400'],
            ['account_no' => '71318', 'description' => 'Meals Supplies', 'parent_account_no' => '70300'],
            ['account_no' => '72001', 'description' => 'Loss on write-down inventory', 'parent_account_no' => '71113'],
            ['account_no' => '72002', 'description' => 'Bad Debt Expense', 'parent_account_no' => '71113'],
            ['account_no' => '72003', 'description' => 'Loss on Disposal of Assets', 'parent_account_no' => '71113'],
            ['account_no' => '72004', 'description' => 'Tuition Waiver Expense', 'parent_account_no' => '71113'],
        ];

        foreach ($accounts as $account) {
            ChartOfAccount::updateOrCreate(
                ['account_no' => $account['account_no']],
                ['description' => $account['description']]
            );
        }

        foreach ($accounts as $account) {
            if (empty($account['parent_account_no'])) {
                continue;
            }

            $parent = ChartOfAccount::where('account_no', $account['parent_account_no'])->first();
            $child = ChartOfAccount::where('account_no', $account['account_no'])->first();

            if ($parent && $child && $child->parent_id !== $parent->id) {
                $child->update(['parent_id' => $parent->id]);
            }
        }
    }
}
